version: '3'
services:
  datadog:
    image: datadog/agent:latest
    ports:
      - 8126:8126
      - 8125:8125/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - SD_BACKEND=docker
      - DD_LOGS_ENABLED=true
      - DD_SITE=datadoghq.com
      - DOCKER_CONTENT_TRUST=1
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true